//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ta3lim.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Concern
    {
        public int id { get; set; }
        public Nullable<int> Employeeid { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·‘ﬂÊÏ")]
        [DisplayName("«·‘ﬂÊÏ")]
        public string Concern1 { get; set; }
        [DisplayName("«· «—ÌŒ")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/p/yyyy}")]
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
