//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ta3lim.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeeType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeType()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int id { get; set; }
        [Required]
        [DisplayName("«·‰Ê⁄")]
        public string Type { get; set; }
        [DisplayName("„œŒ· „⁄·Ê„« ")]
        public Nullable<bool> Basics { get; set; }
        [DisplayName("„œÌ—")]
        public Nullable<bool> Managment { get; set; }
        [DisplayName("„ÊÃÂ")]
        public Nullable<bool> Guidence { get; set; }
        [DisplayName("«” «–")]
        public Nullable<bool> Teaching { get; set; }
        [DisplayName("„—«ﬁ»")]
        public Nullable<bool> Observing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
