//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ta3lim.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Centers = new HashSet<Center>();
            this.Concerns = new HashSet<Concern>();
            this.DailyActivities = new HashSet<DailyActivity>();
            this.Stages = new HashSet<Stage>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·«”„")]
        [DisplayName("«”„ «·„ÊŸ›")]
        public string name { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·ﬂ‰Ì…")]
        [DisplayName("ﬂ‰Ì… «·„ÊŸ›")]
        public string surname { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/p/yyyy}")]

        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«·  «—ÌŒ «·Ê·«œ…")]
        [DisplayName(" «—ÌŒ «·Ê·«œ…")]
        public Nullable<System.DateTime> BDate { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «·‘Â«œ…")]
        [DisplayName("«·‘Â«œ…")]
        public string Certificate { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· ‰Ê⁄ «·‘Â«œ…")]
        [DisplayName("‰Ê⁄ «·‘Â«œ…")]
        public string CType { get; set; }
        [DisplayName("«·Õ«·…")]
        public string State { get; set; }
        public Nullable<int> Centerid { get; set; }
        public Nullable<int> Periodid { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«·  «—ÌŒ «·»œ¡")]
        [DisplayName(" «—ÌŒ «·»œ¡")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/p/yyyy}")]

        public Nullable<System.DateTime> SDate { get; set; }
        [DisplayName(" «—ÌŒ «·«‰ Â«¡")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/p/yyyy}")]

        public Nullable<System.DateTime> EDate { get; set; }
        public Nullable<int> Job { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Center> Centers { get; set; }
        public virtual Center Center { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concern> Concerns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DailyActivity> DailyActivities { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual Period Period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stage> Stages { get; set; }
    }
}
