//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ta3lim.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Period
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Period()
        {
            this.Regiments = new HashSet<Regiment>();
            this.Employees = new HashSet<Employee>();
        }
    
        public int id { get; set; }


        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «”„ «·› —…")]
        [DisplayName("«”„ «·› —…")]
        public string Name { get; set; }


        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· “„«‰ «·»œ¡")]
        [DisplayName("“„«‰ «·»œ¡")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh\\:mm}")]
        public Nullable<System.TimeSpan> StartingTime { get; set; }


        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· “„«‰ «·«‰ Â«¡")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:hh\\:mm}")]
        [DisplayName("“„«‰ «·«‰ Â«¡")]

        public Nullable<System.TimeSpan> Enh2ime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Regiment> Regiments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
