//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ta3lim.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Presence
    {
        public int id { get; set; }
        [Required]
        [DisplayName(" «—ÌŒ «·€Ì«»")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/p/yyyy}")]

        public Nullable<System.DateTime> Date { get; set; }
        [DisplayName("«·‘—Õ")]
        public string Desc { get; set; }
        public Nullable<int> Studentid { get; set; }
        public Nullable<bool> Lesson1 { get; set; }
        public Nullable<bool> Lesson2 { get; set; }
        public Nullable<bool> Lesson3 { get; set; }
        public Nullable<bool> Lesson4 { get; set; }
        public Nullable<bool> Lesson5 { get; set; }
        public Nullable<bool> Lesson6 { get; set; }
        public Nullable<bool> Lesson7 { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
