//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ta3lim.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Stage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stage()
        {
            this.Examinations = new HashSet<Examination>();
            this.Students = new HashSet<Student>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«· «”„ «·„—Õ·… ")]
        [DisplayName("«”„ «·„—Õ·…")]
        public string StageName { get; set; }
        public Nullable<int> Managerid { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«·  «—ÌŒ «·»œ¡ ")]
        [DisplayName(" «—ÌŒ «·»œ¡")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/p/yyyy}")]

        public Nullable<System.DateTime> SDate { get; set; }
        [Required(ErrorMessage = "Ì—ÃÏ «œŒ«·  «—ÌŒ «·«‰ Â«¡ ")]
        [DisplayName(" «—ÌŒ «·«‰ Â«¡")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/p/yyyy}")]

        public Nullable<System.DateTime> EDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examination> Examinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
