//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ta3lim.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Examinations = new HashSet<Examination>();
            this.Presences = new HashSet<Presence>();
        }
    
        public int id { get; set; }
        [Required]
        [DisplayName(" «—ÌŒ «·Ê·«œ…")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/p/yyyy}")]

        public Nullable<System.DateTime> BDate { get; set; }
        [Required]
        [DisplayName("«”„ «·ÿ«·»")]
        public string Name { get; set; }
        [Required]
        [DisplayName("ﬂ‰Ì… «·ÿ«·»")]
        public string Surname { get; set; }
        [Required]
        [DisplayName("«·‘Â«œ…")]
        public string Certificate { get; set; }
        [Required]
        [DisplayName("«·⁄·«„…")]
        public Nullable<double> Mark { get; set; }
        [DisplayName("«·Õ«·…")]
        public string State { get; set; }
        [Required]
        public Nullable<int> Centerid { get; set; }
        [Required]
        public Nullable<int> Stageid { get; set; }
        [Required]
        public Nullable<int> Regimentid { get; set; }
        [Required]
        [DisplayName(" «—ÌŒ «·»œ¡")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/p/yyyy}")]

        public Nullable<System.DateTime> SDate { get; set; }
        [DisplayName(" «—ÌŒ «·«‰ Â«¡")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/p/yyyy}")]

        public Nullable<System.DateTime> EDate { get; set; }
    
        public virtual Center Center { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examination> Examinations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Presence> Presences { get; set; }
        public virtual Regiment Regiment { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
